export const ADD_STAFFS = "ADD_STAFFS"; //Add staffs into store
export const STAFFS_LOADING = "STAFFS_LOADING"; //Fetch Staffs from server
export const STAFFS_FAILED = "STAFFS_FAILED"; //Failed to fetch Staffs from server
export const ADD_DEPTS = "ADD_DEPTS";
export const DEPTS_LOADING = "DEPTS_LOADING";
export const DEPTS_FAILED = "DEPTS_FAILED";
export const ADD_STAFF = "ADD_STAFF";
export const ADD_SALARY = "ADD_SALARY";
export const SALARY_LOADING = "SALARY_LOADING";
export const SALARY_FAILED = "SALARY_FAILED";
export const UPDATE_STAFF = "UPDATE_STAFF";
