export const ADD_COMMENT = "ADD_COMMENT";
export const DISHES_LOADING = "DISHES_LOADING"; //CURRENT DISHES FETCHED FROM SERVER
export const DISHES_FAILED = "DISHES_FAILED"; //FAILED TO FETCHED DISHES FROM SERVER
export const ADD_DISHES = "ADD_DISHES"; // ADD INTO YOUR STORE
